language: go

go:
  - 1.6.3
  - tip
install:
  - go get github.com/revel/revel
  - go get github.com/revel/cmd/revel
  - go get github.com/go-sql-driver/mysql
  - go get github.com/jinzhu/gorm
