language: go

go:
  - 1.6.3
  - tip
services:
  - mysql
install:
  - go get github.com/revel/revel
  - go get github.com/revel/cmd/revel
  - go get github.com/go-sql-driver/mysql
  - go get github.com/jinzhu/gorm
before_script:
  - mysql -e 'create database petconnect;'
script:
  - revel test github.com/nicolasgaraza/petConnect
